openapi: 3.0.2
info:
  title: gen
  version: 1.0.0
servers:
- url: http://127.0.0.1
paths:
  /calculateBMI:
    get:
      operationId: calculateBMI
      parameters:
      - name: height
        in: query
        schema:
          type: number
          format: double
        required: true
      - name: weight
        in: query
        schema:
          type: number
          format: double
        required: true
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: number
                format: double
